"""Create user table

Revision ID: baaed0e17ffa
Revises: 
Create Date: 2025-09-02 20:18:17.903988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baaed0e17ffa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex_assigned_at_birth', sa.String(), nullable=True),
    sa.Column('primary_health_goal', sa.String(), nullable=True),
    sa.Column('exercise_hours_yesterday', sa.Float(), nullable=True),
    sa.Column('sleep_hours_last_night', sa.Float(), nullable=True),
    sa.Column('had_sleep_disturbances', sa.Boolean(), nullable=True),
    sa.Column('feels_thirsty_at_night', sa.Boolean(), nullable=True),
    sa.Column('overall_mood_rating', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.String(), nullable=True),
    sa.Column('focus_rating', sa.Integer(), nullable=True),
    sa.Column('forgets_things_often', sa.Boolean(), nullable=True),
    sa.Column('brain_fog_severity', sa.Integer(), nullable=True),
    sa.Column('current_energy_rating', sa.Integer(), nullable=True),
    sa.Column('most_energized_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
